namespace FluentMigrator.Builders.Create.StoredProcedure
{
	public interface ICreateStoredProcedureParameterOptionOrWithParameterOrDefinitionSyntax : ICreateStoredProcedureWithColumnOrDefinitionSyntax
	{
		ICreateStoredProcedureWithColumnOrDefinitionSyntax WithDefaultValue(object value);
	}
}